### ISSUE TITLE
How to equip Bottom Dollar jacket & The Bottom Dollar outfit?

### ISSUE THREAD

**Issue by kevin007-tech** [YimMenu-Lua/UnlockEverything#22]
Hey man:

How do I equip the bottom dollar jacket & The Bottom Dollar outfit? I’ve been to ponsonbys in the game but can’t find where it’s located at in outfits! Please help!

Thanks!
 
 Every time I press unlock all it doesn’t unlock the bottom dollar jacket or bottom dollar outfit!

**Comment by ShinyWasabi** [comment]
They are locked behind a G9EC lock hash. All the next-gen clothing items use these hashes. So even if you unlock them, they won't be visible in the shop.
mp_m_freemode_01_mp2024_01_shop.meta:
```xml
<lockHash>CU_SUM24_CLOTHES_G9EC</lockHash>
<cost value="0" />
<textLabel>CLO_SDM_U_16_0</textLabel>
<uniqueNameHash>DLC_MP_SUM24_M_JBIB_16_0</uniqueNameHash>
<eShopEnum>CLO_SHOP_LOW</eShopEnum>
<locate value="285" />
<scriptSaveData value="0" />
<!-- ... -->
<lockHash>CU_SUM24_CLOTHES_G9EC</lockHash>
<cost value="99" />
<textLabel>CLO_SDM_O_10</textLabel>
<uniqueNameHash>DLC_MP_SUM24_M_OUTFIT_10</uniqueNameHash>
<eShopEnum>CLO_SHOP_LOW</eShopEnum>
<locate value="282" />
```
You can make them visible in the shop by changing the hash to the normal one (`CU_SUM24_CLOTHES`), but they won't appear on you since they don't have textures. There are some exceptions to this though, where R* leaves the textures for some next-gen clothes in the files.

**Comment by gir489returns** [comment]
@ShinyWasabi Sounds like another Hao's Special Works situation. I wonder if other people in the game will crash if you wear it? Thanks for the explanation.

**Comment by kevin007-tech** [comment]
> They are locked behind a G9EC lock hash. All the next-gen clothing items use these hashes. So even if you unlock them, they won't be visible in the shop. mp_m_freemode_01_mp2024_01_shop.meta:
> 
> ```
> <lockHash>CU_SUM24_CLOTHES_G9EC</lockHash>
> <cost value="0" />
> <textLabel>CLO_SDM_U_16_0</textLabel>
> <uniqueNameHash>DLC_MP_SUM24_M_JBIB_16_0</uniqueNameHash>
> <eShopEnum>CLO_SHOP_LOW</eShopEnum>
> <locate value="285" />
> <scriptSaveData value="0" />
> 
> <lockHash>CU_SUM24_CLOTHES_G9EC</lockHash>
> <cost value="99" />
> <textLabel>CLO_SDM_O_10</textLabel>
> <uniqueNameHash>DLC_MP_SUM24_M_OUTFIT_10</uniqueNameHash>
> <eShopEnum>CLO_SHOP_LOW</eShopEnum>
> <locate value="282" />
> ```
> 
> You can make them visible in the shop by changing the hash to the normal one (`CU_SUM24_CLOTHES`), but they won't appear on you since they don't have textures. There are some exceptions to this though, where R* leaves the textures for some next-gen clothes in the files.

That's kind of silly like why don't they let PC player's unlock the bottom dollar jacket/bottom dollar outfit? Why only PS5 & Xbox Series XIS?
