### ISSUE TITLE
the Snowball Launcher can't hide it from the weapons locker

### ISSUE THREAD

**Issue by shimmered** [YimMenu-Lua/UnlockEverything#29]

**Comment by ShinyWasabi** [comment]
You're probably using FSL which causes the `buy_weapon` function to fail. You can directly modify the stat.

**Comment by ShinyWasabi** [comment]
Fixed by https://github.com/YimMenu-Lua/UnlockEverything/commit/b73222ecd7b60695272a1fc6b2fb3dd784f64e7a
