### ISSUE TITLE
There is no way to start stealing from the new update.

### ISSUE THREAD

**Issue by Roman136-72** [YimMenu-Lua/UnlockEverything#7]
The top screen is empty, on the bottom monitor of the computer it says “you are participating in a hijacking”, when canceling the hijacking it says that there are no active hijackings. Dax’s work "Call me" was also reset to 10 co
![1](https://github.com/YimMenu-Lua/UnlockEverything/assets/155800535/537e59c7-ac20-4c48-8e9e-250b4f43a915)
![2](https://github.com/YimMenu-Lua/UnlockEverything/assets/155800535/de94af33-08be-47df-a330-100fc4f7f0cf)
![3](https://github.com/YimMenu-Lua/UnlockEverything/assets/155800535/82783f81-0052-4be0-92be-7dd0662f944a)
mpleted tasks.

**Comment by visionary2709** [comment]
Here is a solution, just set the following stats (int) to 0 and it will allow you to start a mission again 

MPX_SALV23_GEN_BS
MPX_SALV23_INST_PROG
MPX_SALV23_SCOPE_BS

For the trophy that is reset, you can do the same, just change the value of the statistic to the required one, I think it is 50 and that's it. 

MPX_AWD_CALLME

**Comment by Roman136-72** [comment]
Everything is fixed now. Thank you! I wish the development of your project. You are best!

**Comment by Canarion74** [comment]
Hola buenas tardes.Espero que esté bien.Si por favor me pueden ayudar explicandome como solución el problema ,lo he intentado como lo explican usted pero me da que hago algo mal ,tengo mis dos avatares igual es decir el desguace me sale como le pasó a roman136-72.Un saludo y muchas gracias de antemano.

**Comment by Canarion74** [comment]
Buenas noches. Muchas gracias por la teoría y los códigos. No me funcionaba porque pille el editor viejo.Ya lo solucioné. Ya tengo mis desguace funcionando. Muchas gracias. Ya que los señores del dicho juego les digo el problema y no me solucionan nada ya me paso en su dia con el taller, la agencia y la sede.
