### ISSUE TITLE
VIP Agency

### ISSUE THREAD

**Issue by Roman136-72** [YimMenu-Lua/UnlockEverything#8]
The total number of completed security contracts is 20. What are the statistics for editing them?

**Comment by gir489returns** [comment]
I have no idea what you're talking about.

**Comment by Roman136-72** [comment]
about it
![IMG_3960](https://github.com/YimMenu-Lua/UnlockEverything/assets/155800535/c18019a0-ba5d-4663-8c25-76ce75e934ab)

**Comment by Roman136-72** [comment]
Как их можно увеличить до 201 примерно? А то в данном случае выплаты за игровые сутки рассчитываются за 20 заданий и составляют примерно 2000.

**Comment by gir489returns** [comment]
Можно изменить вручную. Строка 656, с 20 на 201, или изменить в самом YimMenu: Сеть -> Статистика, $MPX_FIXER_COUNT на ввод со значением 201.

**Comment by Roman136-72** [comment]
Спасибо!
